apiVersion: v1
kind: Service #What kind of object you want to create
metadata: #Data that helps uniquely identify the object
  name: greetingserver
spec: #What state you desire for the object
  selector:
    app: greetingserver
  ports:
    - port: 8080  #port at which service is internally available
      targetPort: 8080 #port of container
      name: http
  #    nodePort: 30001  # port at which service is externally available  range 30000- 32767
  type: NodePort
