apiVersion: v1
kind: Service #What kind of object you want to create
metadata: #Data that helps uniquely identify the object
  name: projectms-service
spec: #What state you desire for the object
  selector:
    app: projectms
  ports:
    - port: 8586  #port at which service is internally available
      targetPort: 8586 #port of container
     # nodePort: 30000  # port at which service is externally available  range 30000- 32767 
  type: LoadBalancer
