apiVersion: apps/v1 #version of the Kubernetes API you're using to create this object
kind: Deployment  #What kind of object you want to create
metadata: #Data that helps uniquely identify the object
   name: empms-deployment

spec: #What state you desire for the object
  selector:
    matchLabels:
      app: empms


  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: empms
    spec:   #What state you desire for the object

      containers:
      - name: empms #container name
        image: 'gcr.io/vinproject-8/empms' #image name
        ports:
        - containerPort: 8587 # nginx runs on port 80
