apiVersion: v1
kind: Service #What kind of object you want to create
metadata: #service name,Data that helps uniquely identify the object
  name: customerms
spec: #What state you desire for the object
  selector:
    app: customerms
  ports:
    - port: 8484  #port at which service is internally available
      targetPort: 8484 #port of container
      #nodePort: 30001  # port at which service is externally available  range 30000- 32767 
      name: http
  type: NodePort
